all-versions:
- 1.0.0
- 1.0.1
- 1.0.2
- 1.0.3
- 1.0.4
- 1.0.5
- 1.0.6
author: Fabrizio Ferrai
basic-deps:
  aeson: '>=1.0.0.0 && <2.2'
  base: '>=4.11.0.0 && <5'
  containers: '>=0.5.8.0 && <0.7'
  dhall: '>=1.38.0 && <1.43'
  dhall-openapi: '>=0'
  directory: '>=1.3.0.0 && <1.4'
  filepath: '>=1.4 && <1.5'
  megaparsec: '>=7.0 && <10'
  optparse-applicative: '>=0.14.3.0 && <0.19'
  parser-combinators: '>=0'
  prettyprinter: '>=1.7.0 && <1.8'
  scientific: '>=0.3.0.0 && <0.4'
  sort: '>=1.0 && <1.1'
  text: '>=0.11.1.0 && <2.1'
  vector: '>=0.11.0.0 && <0.14'
changelog: ''
changelog-type: ''
description: |-
  This package provides an `openapi-to-dhall` program that converts an
  OpenAPI specification to a Dhall package containing types, defaults, and
  schemas for that API.
description-type: haddock
hash: eba6400b1835bad2eab81c3912ab2126299ab487225e6ae24a245fa9e4cbfff7
homepage: https://github.com/dhall-lang/dhall-haskell/tree/master/dhall-openapi#dhall-openapi
latest: 1.0.6
license-name: BSD-3-Clause
maintainer: GenuineGabriella@gmail.com
synopsis: Convert an OpenAPI specification to a Dhall package
test-bench-deps: {}
