homepage: https://github.com/dhall-lang/dhall-haskell/tree/master/dhall-openapi#dhall-openapi
changelog-type: ''
hash: df6b60689490f9ecfaa684f3911345624563acaeece11e89f8b28278dcb1731d
test-bench-deps: {}
maintainer: Gabriel439@gmail.com
synopsis: Convert an OpenAPI specification to a Dhall package
changelog: ''
basic-deps:
  base: '>=4.11.0.0 && <5'
  parser-combinators: -any
  dhall: '>=1.38.0 && <1.39'
  text: '>=0.11.1.0 && <1.3'
  megaparsec: '>=7.0 && <9.1'
  filepath: '>=1.4 && <1.5'
  containers: '>=0.5.8.0 && <0.7'
  dhall-openapi: -any
  sort: ==1.0.*
  prettyprinter: '>=1.7.0 && <1.8'
  optparse-applicative: '>=0.14.3.0 && <0.17'
  scientific: '>=0.3.0.0 && <0.4'
  aeson: '>=1.0.0.0 && <1.6'
  vector: '>=0.11.0.0 && <0.13'
  directory: '>=1.3.0.0 && <1.4'
all-versions:
- 1.0.0
author: Fabrizio Ferrai
latest: 1.0.0
description-type: haddock
description: |-
  This package provides an `openapi-to-dhall` program that converts an
  OpenAPI specification to a Dhall package containing types, defaults, and
  schemas for that API.
license-name: BSD-3-Clause
