homepage: https://github.com/haskell-gi/haskell-gi
changelog-type: markdown
hash: 530297180b38b9196796a5802351015582d1f147178efe1a3699bac4dff3293c
test-bench-deps: {}
maintainer: Iñaki García Etxebarria (garetxe@gmail.com)
synopsis: GtkosxApplication bindings
changelog: ! '### 2.0.15


  + Remove enable-overloading flags, and use instead explicit CPP checks for ''haskell-gi-overloading-1.0'',
  see [how to disable overloading](https://github.com/haskell-gi/haskell-gi/wiki/Overloading\#disabling-overloading).


'
basic-deps:
  haskell-gi-base: ==0.21.*
  bytestring: ! '>=0.10 && <1'
  haskell-gi-overloading: <1.1
  base: ! '>=4.7 && <5'
  text: ! '>=1.0 && <2'
  gi-gtk: ==3.0.*
  gi-gobject: ==2.0.*
  containers: ! '>=0.5 && <1'
  haskell-gi: ==0.21.*
  transformers: ! '>=0.4 && <1'
  gi-gdkpixbuf: ==2.0.*
all-versions:
- '2.0.4'
- '2.0.5'
- '2.0.6'
- '2.0.7'
- '2.0.8'
- '2.0.9'
- '2.0.10'
- '2.0.11'
- '2.0.12'
- '2.0.13'
- '2.0.14'
- '2.0.15'
author: Will Thompson, Iñaki García Etxebarria and Jonas Platte
latest: '2.0.15'
description-type: markdown
description: ! '# Documentation

  Autogenerated documentation for this package can be found at


  [https://hackage.haskell.org/package/gi-gtkosxapplication-2.0.15/docs/GI-GtkosxApplication.html](https://hackage.haskell.org/package/gi-gtkosxapplication-2.0.15/docs/GI-GtkosxApplication.html)


  For general documentation on using [haskell-gi](https://github.com/haskell-gi/haskell-gi)
  based bindings, see [the project page](https://github.com/haskell-gi/haskell-gi)
  or [the Wiki](https://github.com/haskell-gi/haskell-gi/wiki).

'
license-name: LGPL-2.1
