all-versions:
- 0.1.0.0
- 0.1.0.1
- 0.1.1.0
author: Robert Hensing
basic-deps:
  Cabal: '>=2.2.0.0'
  base: '>=4 && <5'
  containers: '>=0'
  lens: '>=0'
  process: '>=0'
changelog: |
  # Revision history for cabal-pkg-config-version-hook

  ## Unreleased

  * Fix support for Cabal 3.12.1.0, which would otherwise not pass defines to inline C/C++ code (e.g. inline-c-cpp)

  ## 0.1.0.1 -- 2023-06-28

  * Fix an incomplete pattern match

  ## 0.1.0.0 -- 2022-03-07

  * First version. Main feature is room for improvement.
changelog-type: markdown
description: |2

  # A Cabal setup hook for pkg-config version info

  Cabal doesn't natively give access to version information from `pkg-config` (yet?). This setup hook gets the version and makes it available via Haskell CPP and C/C++ macros, as well as setting Cabal flags automatically.
description-type: markdown
hash: 329290c8fd06f57ca273e478f192b23eb3ade1e17fb69b018d82dc1c56d9697b
homepage: https://github.com/hercules-ci/hercules-ci-agent/tree/master/cabal-pkg-config-version-hook#readme
latest: 0.1.1.0
license-name: BSD-3-Clause
maintainer: info@hercules-ci.com
synopsis: Make Cabal aware of pkg-config package versions
test-bench-deps: {}
