homepage: https://github.com/composite-hs/composite#readme
changelog-type: ''
hash: 888c7be1e88d8134fee87da8a82725c8b2773b9c03cb32e61632db198b53b223
test-bench-deps:
  insert-ordered-containers: '>=0.2.1.0 && <0.3'
  composite-swagger: -any
  base: '>=4.12 && <5'
  composite-base: -any
  hspec: -any
  text: '>=1.2.2.2 && <1.3'
  vinyl: '>=0.5.3 && <0.15'
  lens: '>=4.15.4 && <5.3'
  swagger2: '>=2.1.6 && <2.9'
  QuickCheck: -any
  composite-aeson: -any
  template-haskell: '>=2.11.1.0 && <2.19'
maintainer: oss@vitalbio.com
synopsis: Swagger for Vinyl records
changelog: ''
basic-deps:
  insert-ordered-containers: '>=0.2.1.0 && <0.3'
  base: '>=4.12 && <5'
  composite-base: ==0.8.*
  text: '>=1.2.2.2 && <1.3'
  vinyl: '>=0.5.3 && <0.15'
  lens: '>=4.15.4 && <5.3'
  swagger2: '>=2.1.6 && <2.9'
  template-haskell: '>=2.11.1.0 && <2.19'
all-versions:
- 0.5.4.0
- 0.5.5.0
- 0.6.0.0
- 0.6.1.0
- 0.6.2.0
- 0.7.0.0
- 0.7.1.0
- 0.7.2.0
- 0.7.3.0
- 0.7.4.0
- 0.7.5.0
- 0.8.0.0
- 0.8.1.0
- 0.8.2.0
- 0.8.2.1
- 0.8.2.2
author: Dan Fithian
latest: 0.8.2.2
description-type: haddock
description: Integration between Swagger and Vinyl records allowing easily derivable/explicit
  Swagger definitions for records.
license-name: BSD-3-Clause
