homepage: https://github.com/protoben/config-parser
changelog-type: markdown
hash: 287df8a34d30b131e87a7add5f1a35e30f9c2d61351155b1e82b71cdbf641a97
test-bench-deps:
  extra: ! '>=1.5 && <1.7'
  base: ! '>=4.9 && <4.11'
  hspec: ! '>=2.4 && <2.5'
  text: ! '>=1.2 && <1.3'
  parsec: ! '>=3.1 && <3.2'
  lens: ! '>=4.15 && <4.16'
maintainer: protob3n@gmail.com
synopsis: ! 'Parse config files using parsec and generate parse errors

  on unhandled keys'
changelog: ! "# Revision history for config-parser\n\n## 1.2.0.0  -- 2018-1-20\n\n*
  Fixed incorrect parsing error when invalid key appeared at beginning of file.\n*
  Added `keyIdentifier` field to `ConfigParser` to facilitate more accurate\n  invalid-key
  messages.\n\n## 1.1.0.1  -- 2018-1-20\n\n* Fixed some unexpected parsing behavior
  w/r/t line-ends.\n* Made bounded parser fail before consuming input so descriptive
  expectation is\n  shown in error message.\n\n## 1.1.0.0  -- 2018-1-19\n\n* Made
  parsing errors significantly more informative.\n* The `keyValue` parser in `ConfigParser`
  now takes a `Parser Key`, rather than\n  a `Key`, to facilitate easier detection
  of bad keys.\n* Fixed some broken haddocks.\n\n## 1.0.0.0  -- 2017-12-04\n\n* Removed
  'ConfigParser' constructor with janky call to 'error'. Non-unique keys\n  will now
  cause parsing to fail, instead.\n* Duplicate keys in config files will now cause
  parsing to fail.\n* 'ConfigOption' now has a 'required' field to specify that omitting
  a\n  particular key from a config file is an error. Omiting required keys causes\n
  \ parsing to fail.\n* The 'boundedIntegral' parser is now correctly exported.\n\n##
  0.2.0.0  -- 2017-10-31\n\n* First version. Released on an unsuspecting world.\n"
basic-deps:
  base: ! '>=4.9 && <4.11'
  text: ! '>=1.2 && <1.3'
  parsec: ! '>=3.1 && <3.2'
all-versions:
- '0.1.0.0'
- '0.1.0.1'
- '0.1.0.2'
- '0.1.0.3'
- '0.1.0.4'
- '0.1.0.5'
- '0.1.0.6'
- '0.2.0.0'
- '1.0.0.0'
- '1.1.0.0'
- '1.1.0.1'
- '1.2.0.0'
author: Ben Hamlin
latest: '1.2.0.0'
description-type: haddock
description: ! 'This is yet another entry in Haskell''s enourmous collection

  of config-file parsing libraries. It lacks many of the

  bells and whistles of other config-file parsing libraries,

  such as hierarchical sections and on-the-fly reloading. On

  the other hand, it has a combination of features I was

  unable to find in other libraries:


  * Keys and values are parsed with configurable parsec

  parsers, resulting in flexible syntax and pretty

  error messages.


  * Custom parsers can be created with parsec to handle

  values of any type.


  * Keys that aren''t explicitly handled result in parse

  errors.


  If you don''t need all of these features, there are

  probably better libraries out there for you. If you''re free

  to use its idiosyncratic file format, the config-value

  library, in particular, is excelent.'
license-name: MIT
