homepage: github.com/protoben/config-parser
changelog-type: markdown
hash: af6902493e34fcd246887835d0b1ba91face18132f9cd7664d4cdb47a2cd8f05
test-bench-deps:
  base: ! '>=4.9 && <4.10'
  hspec: ! '>=2.4 && <2.5'
  text: ! '>=1.2 && <1.3'
  parsec: ! '>=3.1 && <3.2'
  lens: ! '>=4.15 && <4.16'
maintainer: protob3n@gmail.com
synopsis: ! 'Parse config files using parsec and generate parse errors

  on unhandled keys'
changelog: ! '# Revision history for config-parser


  ## 0.1.0.0  -- YYYY-mm-dd


  * First version. Released on an unsuspecting world.

'
basic-deps:
  base: ! '>=4.9 && <4.10'
  parsec: ! '>=3.1 && <3.2'
all-versions:
- '0.1.0.0'
- '0.1.0.1'
- '0.1.0.2'
- '0.1.0.3'
author: Ben Hamlin
latest: '0.1.0.3'
description-type: haddock
description: ! 'This is yet another entry in Haskell''s enourmous collection

  of config-file parsing libraries. It lacks many of the

  bells and whistles of other config-file parsing libraries,

  such as hierarchical sections and on-the-fly reloading. On

  the other hand, it has a combination of features I was

  unable to find in other libraries:

  * Keys and values are parsed with configurable parsec

  parsers, resulting in flexible syntax and pretty

  error messages.

  * Custom parsers can be created with parsec to handle

  values of any type.

  * Keys that aren''t explicitly handled result in parse

  errors.

  If you don''t need all of these features, there are

  probably better libraries out there for you. If you''re free

  to use its idiosyncratic file format, the config-value

  library, in particular, is excelent.'
license-name: MIT
