homepage: https://github.com/haskell-servant/servant-swagger-ui
changelog-type: markdown
hash: 005c1083d580e9e73668e8184e3bbe02aac0b67d5a8500b147dfa3bd237d66a5
test-bench-deps: {}
maintainer: haskell-servant-maintainers@googlegroups.com
synopsis: Servant swagger ui core components
changelog: |
  # 0.3.5

  - Generalize `SwaggerSchemaUI` and `swaggerSchemaUIServerImpl` to support arbitrary `Value` instead
    of hardcoded `Swagger` type.

  # 0.3.3

  - Add `swaggerSchemaUIServerImpl'`

  # 0.3.1

  - Support `servant-0.14`
basic-deps:
  bytestring: '>=0.10.4.0 && <0.11'
  base: '>=4.7 && <4.15'
  blaze-markup: '>=0.7.0.2 && <0.9'
  text: '>=1.2.3.0 && <1.3'
  servant-server: '>=0.14 && <0.19'
  servant: '>=0.14 && <0.19'
  servant-blaze: '>=0.8 && <0.10'
  transformers: '>=0.3 && <0.6'
  wai-app-static: '>=3.0.1.1 && <3.2'
  aeson: '>=0.8.0.2 && <1.6'
  http-media: '>=0.7.1.3 && <0.9'
  transformers-compat: '>=0.3 && <0.7'
all-versions:
- '0.3'
- 0.3.1
- 0.3.2
- 0.3.3
- 0.3.4
- 0.3.5
author: Oleg Grenrus <oleg.grenrus@iki.fi>
latest: 0.3.5
description-type: haddock
description: |-
  Provide embedded swagger UI for servant and swagger (i.e. servant-swagger)

  See servant-swagger-ui, servant-swagger-ui-jensoleg or
  servant-swagger-ui-redoc for "concrete" implementations.
license-name: BSD-3-Clause
