all-versions:
- '0.3'
- 0.3.1
- 0.3.2
- 0.3.3
- 0.3.4
- 0.3.5
author: Oleg Grenrus <oleg.grenrus@iki.fi>
basic-deps:
  aeson: '>=0.8.0.2 && <2.3'
  base: '>=4.7 && <4.20'
  blaze-markup: '>=0.7.0.2 && <0.9'
  bytestring: '>=0.10.4.0 && <0.13'
  http-media: '>=0.7.1.3 && <0.9'
  servant: '>=0.14 && <0.21'
  servant-blaze: '>=0.8 && <0.10'
  servant-server: '>=0.14 && <0.21'
  text: '>=1.2.3.0 && <2.2'
  transformers: '>=0.3 && <0.7'
  transformers-compat: '>=0.3 && <0.8'
  wai-app-static: '>=3.0.1.1 && <3.2'
changelog: |
  # 0.3.5

  - Generalize `SwaggerSchemaUI` and `swaggerSchemaUIServerImpl` to support arbitrary `Value` instead
    of hardcoded `Swagger` type.

  # 0.3.3

  - Add `swaggerSchemaUIServerImpl'`

  # 0.3.1

  - Support `servant-0.14`
changelog-type: markdown
description: |-
  Provide embedded swagger UI for servant and swagger (i.e. servant-swagger)

  See servant-swagger-ui, servant-swagger-ui-jensoleg or
  servant-swagger-ui-redoc for "concrete" implementations.
description-type: haddock
hash: 94620b21433a40f813a8b7adb570dfff4e1e8f8b09f1fc00b839d53a4018b338
homepage: https://github.com/haskell-servant/servant-swagger-ui
latest: 0.3.5
license-name: BSD-3-Clause
maintainer: haskell-servant-maintainers@googlegroups.com
synopsis: Servant swagger ui core components
test-bench-deps: {}
