all-versions:
- 0.2.6.0
- 0.2.6.1
- 0.2.7.0
- 0.2.8.0
- 0.2.9.0
- 0.2.10.0
- 0.2.10.1
- 0.2.10.2
author: Julian K. Arni
basic-deps:
  base: '>=4.10 && <4.20'
  lens: '>=4.16.1 && <5.3'
  servant: '>=0.13 && <0.21'
  servant-auth: '>=0.4 && <0.5'
  servant-swagger: '>=1.1.5 && <2'
  swagger2: '>=2.2.2 && <3'
  text: '>=1.2.3.0 && <2.2'
changelog: |
  # Changelog

  All notable changes to this project will be documented in this file.

  The format is based on [Keep a Changelog](http://keepachangelog.com/en/1.0.0/)
  and this project adheres to [PVP Versioning](https://pvp.haskell.org/).

  ## [Unreleased]

  ## [0.2.10.1] - 2020-10-06

  ### Changed

  - Support GHC 8.10 @domenkozar
  - Fix build with swagger 2.5.x @domenkozar

  ## [0.2.10.0] - 2018-06-18

  ### Added

  - Support for GHC 8.4 by @phadej
  - Changelog by @domenkozar
  - #93: Add Cookie in SwaggerSpec API by @domenkozar
  - #42: Add dummy AllHasSecurity Cookie instance by @sordina
changelog-type: markdown
description: |-
  This package provides instances that allow generating swagger2 schemas from
  <https://hackage.haskell.org/package/servant servant>
  APIs that use
  <https://hackage.haskell.org/package/servant-auth servant-auth's> @Auth@ combinator.

  For a quick overview of the usage, see the <https://github.com/haskell-servant/servant/tree/master/servant-auth#readme README>.
description-type: haddock
hash: eda169d986faf562b6f43ac90d48c4fcf895dc235dd002d523ad582ec9be833f
homepage: https://github.com/haskell-servant/servant/tree/master/servant-auth#readme
latest: 0.2.10.2
license-name: BSD-3-Clause
maintainer: jkarni@gmail.com
synopsis: servant-swagger/servant-auth compatibility
test-bench-deps:
  QuickCheck: '>=2.11.3 && <2.15'
  base: '>=0'
  hspec: '>=2.5.5 && <2.12'
  lens: '>=0'
  servant: '>=0'
  servant-auth: '>=0'
  servant-auth-swagger: '>=0'
  servant-swagger: '>=0'
  swagger2: '>=0'
  text: '>=0'
