homepage: https://github.com/haskell-servant/servant-swagger-ui
changelog-type: ''
hash: 84e7ee381d4bf38bc625a7c8ee085a4b2b44bc405c75f4a3b899f1f5066bf0e5
test-bench-deps: {}
maintainer: haskell-servant-maintainers@googlegroups.com
synopsis: ! 'Servant swagger ui: Jens-Ole Graulund theme'
changelog: ''
basic-deps:
  bytestring: ! '>=0.10.4.0 && <0.11'
  file-embed-lzma: ! '>=0 && <0.1'
  base: ! '>=4.7 && <4.12'
  text: ! '>=1.2.0.6 && <1.3'
  servant-server: ! '>=0.4.4.5 && <0.15'
  servant-swagger-ui-core: ! '>=0.3 && <0.4'
  servant: ! '>=0.4.4.5 && <0.15'
  swagger2: ! '>=2.0.1 && <2.4'
all-versions:
- '0.3'
author: Oleg Grenrus <oleg.grenrus@iki.fi>
latest: '0.3'
description-type: haddock
description: ! 'Provide embedded swagger UI for servant and swagger (i.e. servant-swagger)


  Jsn-Ole Graulund theme https://github.com/jensoleg/swagger-org'
license-name: BSD3
