homepage: https://github.com/haskell-servant/servant-swagger-ui
changelog-type: markdown
hash: 35b287bd557161b9f1e5c07bccd6f542c6163e5dfd29ee2220cd24587e701f0c
test-bench-deps: {}
maintainer: haskell-servant-maintainers@googlegroups.com
synopsis: ! 'Servant swagger ui: ReDoc theme'
changelog: ! "- 0.3.2.1.22.2\n    - Update to ReDoc-1.22.2\n    - Add GHC-8.6 support\n
  \   - Drop `servant<0.14` support\n"
basic-deps:
  bytestring: ! '>=0.10.4.0 && <0.11'
  file-embed-lzma: ! '>=0 && <0.1'
  base: ! '>=4.7 && <4.13'
  text: ! '>=1.2.3.0 && <1.3'
  servant-server: ! '>=0.14 && <0.16'
  servant-swagger-ui-core: ! '>=0.3.2 && <0.4'
  servant: ! '>=0.14 && <0.16'
  swagger2: ! '>=2.3.0.1 && <2.4'
all-versions:
- '0.3.0.1.21.2'
- '0.3.2.1.22.2'
author: Oleg Grenrus <oleg.grenrus@iki.fi>
latest: '0.3.2.1.22.2'
description-type: haddock
description: ! 'Provide embedded swagger UI for servant and swagger (i.e. servant-swagger)


  ReDoc theme: https://github.com/Rebilly/ReDoc'
license-name: BSD3
