homepage: https://github.com/haskell-servant/servant-swagger-ui
changelog-type: ''
hash: 67bdb292985a96e5a1210967898a0145c2091b8d29ae1eadfe859fb65359f737
test-bench-deps: {}
maintainer: haskell-servant-maintainers@googlegroups.com
synopsis: ! 'Servant swagger ui: Jens-Ole Graulund theme'
changelog: ''
basic-deps:
  bytestring: ! '>=0.10.4.0 && <0.11'
  file-embed-lzma: ! '>=0 && <0.1'
  base: ! '>=4.7 && <4.13'
  text: ! '>=1.2.3.0 && <1.3'
  servant-server: ! '>=0.14 && <0.17'
  servant-swagger-ui-core: ! '>=0.3.3 && <0.4'
  servant: ! '>=0.14 && <0.17'
  swagger2: ! '>=2.3.0.1 && <2.5'
all-versions:
- '0.3'
- 0.3.2
- 0.3.3
author: Oleg Grenrus <oleg.grenrus@iki.fi>
latest: 0.3.3
description-type: haddock
description: |-
  Provide embedded swagger UI for servant and swagger (i.e. servant-swagger)

  Jsn-Ole Graulund theme https://github.com/jensoleg/swagger-org
license-name: BSD-3-Clause
