homepage: http://github.com/haskell-servant/servant-auth#readme
changelog-type: markdown
hash: c407d1db31a8a5faae830b55b8e074c33d4a3cb74b91982cd43f6d2e3a570e2d
test-bench-deps:
  base: -any
  hspec: '>=2.5.5 && <2.8'
  text: -any
  servant-auth-swagger: -any
  servant-swagger: -any
  servant: -any
  lens: -any
  servant-auth: -any
  swagger2: -any
  QuickCheck: '>=2.11.3 && <2.15'
maintainer: jkarni@gmail.com
synopsis: servant-swagger/servant-auth compatibility
changelog: |
  # Changelog

  All notable changes to this project will be documented in this file.

  The format is based on [Keep a Changelog](http://keepachangelog.com/en/1.0.0/)
  and this project adheres to [PVP Versioning](https://pvp.haskell.org/).

  ## [Unreleased]

  ## [0.2.10.1] - 2020-10-06

  ### Changed

  - Support GHC 8.10 @domenkozar
  - Fix build with swagger 2.5.x @domenkozar

  ## [0.2.10.0] - 2018-06-18

  ### Added

  - Support for GHC 8.4 by @phadej
  - Changelog by @domenkozar
  - #93: Add Cookie in SwaggerSpec API by @domenkozar
  - #42: Add dummy AllHasSecurity Cookie instance by @sordina
basic-deps:
  base: '>=4.10 && <4.15'
  text: '>=1.2.3.0 && <1.3'
  servant-swagger: '>=1.1.5 && <1.8'
  servant: '>=0.13 && <0.19'
  lens: '>=4.16.1 && <5.1'
  servant-auth: ==0.4.*
  swagger2: '>=2.2.2 && <2.7'
all-versions:
- 0.2.6.0
- 0.2.6.1
- 0.2.7.0
- 0.2.8.0
- 0.2.9.0
- 0.2.10.0
- 0.2.10.1
author: Julian K. Arni
latest: 0.2.10.1
description-type: haddock
description: |-
  This package provides instances that allow generating swagger2 schemas from
  <https://hackage.haskell.org/package/servant servant>
  APIs that use
  <https://hackage.haskell.org/package/servant-auth servant-auth's> @Auth@ combinator.

  For a quick overview of the usage, see the <http://github.com/haskell-servant/servant-auth#readme README>.
license-name: BSD-3-Clause
