homepage: https://github.com/phadej/servant-swagger-ui
changelog-type: ''
hash: 1b11bce011fef14ff82f3e1227ce7da2e4074fa693054ec9fb5e8b9e86ca02b6
test-bench-deps: {}
maintainer: Oleg Grenrus <oleg.grenrus@iki.fi>
synopsis: Servant swagger ui core components
changelog: ''
basic-deps:
  bytestring: ! '>=0.10.4.0 && <0.11'
  base: ! '>=4.7 && <4.12'
  blaze-markup: ! '>=0.7.0.2 && <0.9'
  text: ! '>=1.2.0.6 && <1.3'
  servant-server: ! '>=0.4.4.5 && <0.14'
  servant: ! '>=0.5 && <0.14'
  servant-blaze: ! '>=0.4.4.5 && <0.9'
  swagger2: ! '>=2.0.1 && <2.3'
  transformers: ! '>=0.3 && <0.6'
  wai-app-static: ! '>=3.0.1.1 && <3.2'
  http-media: ! '>=0.6.2 && <0.8'
  transformers-compat: ! '>=0.3 && <0.7'
all-versions:
- '0.3'
author: Oleg Grenrus <oleg.grenrus@iki.fi>
latest: '0.3'
description-type: haddock
description: ! 'Provide embedded swagger UI for servant and swagger (i.e. servant-swagger)


  See servant-swagger-ui, servant-swagger-ui-jensoleg or

  servant-swagger-ui-redoc for "concrete" implementations.'
license-name: BSD3
