homepage: https://github.com/phadej/servant-swagger-ui#readme
changelog-type: markdown
hash: f0ebd18498a39b90d9641f845b87778c636c70590d84cbcf36093f6bdd7a675a
test-bench-deps:
  warp: ! '>=3.0.13.1 && <3.3'
  servant-swagger-ui: -any
  wai: ! '>=3.0.3.0 && <3.3'
  base: -any
  text: -any
  servant-swagger: -any
  servant-server: -any
  servant: -any
  lens: ! '>=4.7.0.1 && <4.17'
  base-compat: ! '>=0.6.0 && <0.10'
  swagger2: -any
  transformers: -any
  aeson: ! '>=0.8.0.2 && <1.3'
  transformers-compat: -any
maintainer: Oleg Grenrus <oleg.grenrus@iki.fi>
synopsis: Servant swagger ui
changelog: ! "- 0.2.5.3.9.1\n    - Support `servant-0.13`\n    - Update to `swagger-ui-3.9.1`\n\n-
  0.2.4.3.4.0\n    - Update to `swagger-ui-3.4.0`\n\n- 0.2.4.3.0.20\n    - Update
  to `swagger-ui-3.0.20`\n\n- 0.2.3.2.2.8\n    - Support `servant-0.11`\n\n- 0.2.2.2.2.8\n
  \   - Support `servant-0.10`\n\n- 0.2.1.2.2.8\n    - Update to `swagger-ui-2.2.8`\n
  \   - Add support for [jensoleg](https://github.com/jensoleg/swagger-ui>) theme\n\n-
  0.2.0.2.1.5\n\n    - Introduce `SwaggerSchemaUI`, this fixes\n      [Swagger UI
  does not work when nested](https://github.com/phadej/servant-swagger-ui/issues/8)
  issue\n      by sacrificing some subjective flexibility.\n    - update bundled swagger-ui
  to version 2.1.5\n\n- 0.1.1.2.1.4\n\n    - Documentation and example improvements\n"
basic-deps:
  bytestring: ! '>=0.10.4.0 && <0.11'
  base: ! '>=4.7 && <4.11'
  blaze-markup: ! '>=0.7.0.2 && <0.9'
  text: ! '>=1.2.0.6 && <1.3'
  filepath: ! '>=1.3.0.2 && <1.5'
  servant-swagger: ! '>=1.0.3 && <1.2'
  servant-server: ! '>=0.4.4.5 && <0.14'
  servant: ! '>=0.5 && <0.14'
  servant-blaze: ! '>=0.4.4.5 && <0.9'
  swagger2: ! '>=2.0.1 && <2.3'
  file-embed: ! '>=0.0.9 && <0.1'
  transformers: ! '>=0.3 && <0.6'
  wai-app-static: ! '>=3.0.1.1 && <3.2'
  template-haskell: ! '>=2.9 && <2.13'
  http-media: ! '>=0.6.2 && <0.8'
  transformers-compat: ! '>=0.3 && <0.6'
  directory: ! '>=1.2.1.0 && <1.4'
all-versions:
- '0.1.0.2.1.4'
- '0.1.1.2.1.4'
- '0.2.0.2.1.5'
- '0.2.1.2.2.8'
- '0.2.2.2.2.8'
- '0.2.3.2.2.8'
- '0.2.4.3.0.20'
- '0.2.4.3.4.0'
- '0.2.5.3.9.1'
author: Oleg Grenrus <oleg.grenrus@iki.fi>
latest: '0.2.5.3.9.1'
description-type: markdown
description: ! '# servant-swagger-ui


  *Provide a Swagger UI for your Servant API*


  "[Swagger UI](http://swagger.io/swagger-ui/) allows anyone — be it your development
  team or your end consumers — to visualize and interact with the API’s resources
  without having any of the implementation logic in place."


  [![Build Status](https://travis-ci.org/phadej/servant-swagger-ui.svg?branch=master)](https://travis-ci.org/phadej/servant-swagger-ui)

  [![Hackage](https://img.shields.io/hackage/v/servant-swagger-ui.svg)](http://hackage.haskell.org/package/servant-swagger-ui)

  [![Stackage LTS 5](http://stackage.org/package/servant-swagger-ui/badge/lts-5)](http://stackage.org/lts-5/package/servant-swagger-ui)

  [![Stackage Nightly](http://stackage.org/package/servant-swagger-ui/badge/nightly)](http://stackage.org/nightly/package/servant-swagger-ui)


  ## Example


  ![example screenshot](https://raw.githubusercontent.com/phadej/servant-swagger-ui/master/screenshot.png)


  Check [`example/Main.hs`](https://github.com/phadej/servant-swagger-ui/blob/master/example/Main.hs)
  for an example.


  ## Development


  ### Updating of bundled swagger-ui version:


  - Extract `dist` directory of `swagger-ui` into `swagger-dist-&lt;version&gt;`.
  Remove the `*.map` files.

  - update `extra-source-files` in the `.cabal`

  - move `index.html` into `index.html.tmpl`, do the diff, port the changes

  - search replace the embbeded directory (in `Servant/Swagger/UI.hs`)

  - test it works

'
license-name: BSD3
