homepage: https://github.com/haskell-servant/servant-swagger-ui
changelog-type: markdown
hash: 49d30cbff0960999a31bc2fe944a005890a42a6ffb97434905c66ee3f9352674
test-bench-deps: {}
maintainer: haskell-servant-maintainers@googlegroups.com
synopsis: ! 'Servant swagger ui: ReDoc theme'
changelog: |
  - 0.3.2.1.22.3
      - Update to ReDoc-1.22.3

  - 0.3.3.1.22.2
      - Add `swaggerSchemaUIServer'`

  - 0.3.2.1.22.2
      - Update to ReDoc-1.22.2
      - Add GHC-8.6 support
      - Drop `servant<0.14` support
basic-deps:
  bytestring: ! '>=0.10.4.0 && <0.11'
  file-embed-lzma: ! '>=0 && <0.1'
  base: ! '>=4.7 && <4.14'
  text: ! '>=1.2.3.0 && <1.3'
  servant-server: ! '>=0.14 && <0.17'
  servant-swagger-ui-core: ! '>=0.3.3 && <0.4'
  servant: ! '>=0.14 && <0.17'
  swagger2: ! '>=2.3.0.1 && <2.5'
all-versions:
- 0.3.0.1.21.2
- 0.3.2.1.22.2
- 0.3.3.1.22.2
- 0.3.3.1.22.3
author: Oleg Grenrus <oleg.grenrus@iki.fi>
latest: 0.3.3.1.22.3
description-type: haddock
description: |-
  Provide embedded swagger UI for servant and swagger (i.e. servant-swagger)

  ReDoc theme: https://github.com/Rebilly/ReDoc
license-name: BSD-3-Clause
