homepage: https://github.com/haskell-servant/servant-swagger-ui
changelog-type: markdown
hash: 2944e9863f56228eeac7fe513640b302395fea03a9ea322fc505e993494c41cd
test-bench-deps: {}
maintainer: haskell-servant-maintainers@googlegroups.com
synopsis: Servant swagger ui
changelog: ! "- 0.3.0.3.13.2\n    - Update to `swagger-ui-3.13.2`\n    - Split package
  into multiple packages:\n        - [`servant-swagger-ui-core`](http://hackage.haskell.org/package/servant-swagger-ui-core)\n
  \       - [`servant-swagger-ui-redoc`](http://hackage.haskell.org/package/servant-swagger-ui-redoc)\n
  \       - [`servant-swagger-ui-jensoleg`](http://hackage.haskell.org/package/servant-swagger-ui-jensoleg)\n\n-
  0.2.5.3.9.1\n    - Support `servant-0.13`\n    - Update to `swagger-ui-3.9.1`\n\n-
  0.2.4.3.4.0\n    - Update to `swagger-ui-3.4.0`\n\n- 0.2.4.3.0.20\n    - Update
  to `swagger-ui-3.0.20`\n\n- 0.2.3.2.2.8\n    - Support `servant-0.11`\n\n- 0.2.2.2.2.8\n
  \   - Support `servant-0.10`\n\n- 0.2.1.2.2.8\n    - Update to `swagger-ui-2.2.8`\n
  \   - Add support for [jensoleg](https://github.com/jensoleg/swagger-ui>) theme\n\n-
  0.2.0.2.1.5\n\n    - Introduce `SwaggerSchemaUI`, this fixes\n      [Swagger UI
  does not work when nested](https://github.com/phadej/servant-swagger-ui/issues/8)
  issue\n      by sacrificing some subjective flexibility.\n    - update bundled swagger-ui
  to version 2.1.5\n\n- 0.1.1.2.1.4\n\n    - Documentation and example improvements\n"
basic-deps:
  bytestring: ! '>=0.10.4.0 && <0.11'
  file-embed-lzma: ! '>=0 && <0.1'
  base: ! '>=4.7 && <4.12'
  text: ! '>=1.2.0.6 && <1.3'
  servant-server: ! '>=0.4.4.5 && <0.15'
  servant-swagger-ui-core: ! '>=0.3 && <0.4'
  servant: ! '>=0.4.4.5 && <0.15'
  swagger2: ! '>=2.0.1 && <2.3'
all-versions:
- '0.1.0.2.1.4'
- '0.1.1.2.1.4'
- '0.2.0.2.1.5'
- '0.2.1.2.2.8'
- '0.2.2.2.2.8'
- '0.2.3.2.2.8'
- '0.2.4.3.0.20'
- '0.2.4.3.4.0'
- '0.2.5.3.9.1'
- '0.3.0.3.13.2'
author: Oleg Grenrus <oleg.grenrus@iki.fi>
latest: '0.3.0.3.13.2'
description-type: haddock
description: Provide embedded swagger UI for servant and swagger (i.e. servant-swagger)
license-name: BSD3
