all-versions:
- 1.0.0
- 1.0.1
author: ''
basic-deps:
  aeson: '>=2 && <3'
  base: '>=4.8 && <4.22'
  stratosphere: ==1.0.1
changelog: ''
changelog-type: ''
description: Integration into stratosphere to generate resources and properties for
  AWS OpenSearchServerless
description-type: haddock
hash: a93c8569e1f6c28f7ef145d232ae132f21864e510d138c87fa75dda5493e6e8a
homepage: https://github.com/mbj/stratosphere#readme
latest: 1.0.1
license-name: MIT
maintainer: Markus Schirp
synopsis: Stratosphere integration for AWS OpenSearchServerless.
test-bench-deps: {}
