all-versions:
- 1.0.0
- 1.0.1
author: ''
basic-deps:
  aeson: '>=2 && <3'
  base: '>=4.8 && <4.22'
  stratosphere: ==1.0.1
changelog: ''
changelog-type: ''
description: Integration into stratosphere to generate resources and properties for
  AWS RedshiftServerless
description-type: haddock
hash: cb13acf37f0ae3f853ff6dfdc684b10b475f128495f632755cc003b1128622fe
homepage: https://github.com/mbj/stratosphere#readme
latest: 1.0.1
license-name: MIT
maintainer: Markus Schirp
synopsis: Stratosphere integration for AWS RedshiftServerless.
test-bench-deps: {}
