all-versions:
- 1.0.0
- 1.0.1
author: ''
basic-deps:
  aeson: '>=2 && <3'
  base: '>=4.8 && <4.22'
  stratosphere: ==1.0.1
changelog: ''
changelog-type: ''
description: Integration into stratosphere to generate resources and properties for
  AWS ApplicationAutoScaling
description-type: haddock
hash: 3ea77da6996702826ad64bf30970970e6b4c520ff966d530935446116eec202a
homepage: https://github.com/mbj/stratosphere#readme
latest: 1.0.1
license-name: MIT
maintainer: Markus Schirp
synopsis: Stratosphere integration for AWS ApplicationAutoScaling.
test-bench-deps: {}
