all-versions:
- 1.0.0
author: ''
basic-deps:
  aeson: '>=2 && <3'
  base: '>=4.8 && <4.22'
  stratosphere: ==1.0.0
changelog: ''
changelog-type: ''
description: Integration into stratosphere to generate resources and properties for
  AWS ApplicationInsights
description-type: haddock
hash: 4502251f5ed6d5f5ba852023ecaa30259b1750c3888f0e70220405bc3a11bd83
homepage: https://github.com/mbj/stratosphere#readme
latest: 1.0.0
license-name: MIT
maintainer: Markus Schirp
synopsis: Stratosphere integration for AWS ApplicationInsights.
test-bench-deps: {}
