all-versions:
- 1.0.0
author: ''
basic-deps:
  aeson: '>=2 && <3'
  base: '>=4.8 && <4.22'
  stratosphere: ==1.0.0
changelog: ''
changelog-type: ''
description: Integration into stratosphere to generate resources and properties for
  AWS Config
description-type: haddock
hash: 26487815b756e3453ffe2028845fa09580e988e4279743d50dce53d795168b34
homepage: https://github.com/mbj/stratosphere#readme
latest: 1.0.0
license-name: MIT
maintainer: Markus Schirp
synopsis: Stratosphere integration for AWS Config.
test-bench-deps: {}
