all-versions:
- 1.0.0
author: ''
basic-deps:
  aeson: '>=2 && <3'
  base: '>=4.8 && <4.22'
  stratosphere: ==1.0.0
changelog: ''
changelog-type: ''
description: Integration into stratosphere to generate resources and properties for
  AWS AppConfig
description-type: haddock
hash: 1e63afb3eade5ae79e15b66140b6f370e941f3c74286483e847f41559af85a41
homepage: https://github.com/mbj/stratosphere#readme
latest: 1.0.0
license-name: MIT
maintainer: Markus Schirp
synopsis: Stratosphere integration for AWS AppConfig.
test-bench-deps: {}
