all-versions:
- 1.0.0
author: ''
basic-deps:
  aeson: '>=2 && <3'
  base: '>=4.8 && <4.22'
  stratosphere: ==1.0.0
changelog: ''
changelog-type: ''
description: Integration into stratosphere to generate resources and properties for
  AWS ApplicationAutoScaling
description-type: haddock
hash: 699eb18a27cdf65ef52fe6688c555496c8b3a403d081a4f62184ee3e24e68392
homepage: https://github.com/mbj/stratosphere#readme
latest: 1.0.0
license-name: MIT
maintainer: Markus Schirp
synopsis: Stratosphere integration for AWS ApplicationAutoScaling.
test-bench-deps: {}
