all-versions:
- 1.0.0
- 1.0.1
author: ''
basic-deps:
  aeson: '>=2 && <3'
  base: '>=4.8 && <4.22'
  stratosphere: ==1.0.1
changelog: ''
changelog-type: ''
description: Integration into stratosphere to generate resources and properties for
  AWS ApplicationSignals
description-type: haddock
hash: 3e069bcb2baf45456a3a9c9488553a3443611db4d220224be70482b1c6a0f046
homepage: https://github.com/mbj/stratosphere#readme
latest: 1.0.1
license-name: MIT
maintainer: Markus Schirp
synopsis: Stratosphere integration for AWS ApplicationSignals.
test-bench-deps: {}
