all-versions:
- 1.0.0
- 1.0.1
author: ''
basic-deps:
  aeson: '>=2 && <3'
  base: '>=4.8 && <4.22'
  stratosphere: ==1.0.1
changelog: ''
changelog-type: ''
description: Integration into stratosphere to generate resources and properties for
  AWS Config
description-type: haddock
hash: 5caf8f1a030fe394e7801304762995d021f16be4286855292d53a628a40a8fc1
homepage: https://github.com/mbj/stratosphere#readme
latest: 1.0.1
license-name: MIT
maintainer: Markus Schirp
synopsis: Stratosphere integration for AWS Config.
test-bench-deps: {}
