homepage: https://github.com/hverr/haskell-lxd-client-config#readme
changelog-type: ''
hash: 0003eab9eedd8ec703511d181b04bf50e5caf7c1c507a85280e58fada436a143
test-bench-deps:
  test-framework-hunit: ! '>=0.3 && <1'
  test-framework: ! '>=0.8 && <1'
  base: -any
  text: ! '>=1.2 && <2'
  test-framework-quickcheck2: ! '>=0.3 && <1'
  HUnit: ! '>=1.3 && <2'
  containers: ! '>=0.5 && <1'
  lxd-client-config: -any
  QuickCheck: ! '>=2 && <3'
  yaml: ! '>=0.8 && <1'
maintainer: henriverroken@gmail.com
synopsis: Read the configuration file of the standard LXD client.
changelog: ''
basic-deps:
  base: ! '>=4.7 && <5'
  text: ! '>=1.2 && <2'
  filepath: ! '>=1.4 && <2'
  containers: ! '>=0.5 && <1'
  aeson: -any
  yaml: ! '>=0.8 && <1'
  directory: ! '>=1.2 && <2'
all-versions:
- 0.1.0.0
- 0.1.0.1
author: Henri Verroken
latest: 0.1.0.1
description-type: markdown
description: ! "lxd-client-config\n=================\n\n[![Hackage](https://img.shields.io/hackage/v/lxd-client-config.svg?maxAge=2592000)](https://hackage.haskell.org/package/lxd-client-config)\n[![Stackage
  Nightly](http://stackage.org/package/lxd-client-config/badge/nightly)](http://stackage.org/nightly/package/lxd-client-config)\n[![Stackage
  LTS](http://stackage.org/package/lxd-client-config/badge/lts)](http://stackage.org/lts/package/lxd-client-config)\n\n\n##
  About\nThis Haskell package can read the configuration file of the standard [LXD
  client][lxd-client]. It can thus for example extract information about the configured
  LXD remotes.\n\nLXD is a container manager offering users a similar experience to
  virtual machines, but using Linux containers. See https://github.com/lxc/lxd for
  more information.\n\n  [lxd-client]: https://github.com/lxc/lxd/tree/master/lxc\n"
license-name: GPL-3.0-only
