homepage: http://www.happstack.com/docs/crashcourse/index.html#web-routes
changelog-type: ''
hash: 7d2f62e6bbc3687bdb95a190073f2edd5f4ad8de2ba28233dd62b3720da01c92
test-bench-deps:
  base: ==4.*
  hspec: -any
  text: -any
  HUnit: -any
  web-routes: -any
  QuickCheck: -any
maintainer: partners@seereason.com
synopsis: portable, type-safe URL routing
changelog: ''
basic-deps:
  exceptions: ! '>=0.6.1 && <0.11'
  bytestring: ! '>=0.9 && <0.11'
  split: -any
  base: ! '>=4.9 && <5'
  text: ! '>=0.11 && <1.3'
  parsec: ! '>=2 && <4'
  blaze-builder: ! '>=0.2 && <0.5'
  utf8-string: ! '>=0.3 && <1.1'
  ghc-prim: -any
  mtl: ! '>=2.0 && <2.3'
  http-types: ! '>=0.6 && <0.13'
all-versions:
- 0.22.0
- 0.23.0
- 0.23.1
- 0.23.2
- 0.23.4
- 0.24.1
- 0.25.1
- 0.25.2
- 0.25.3
- 0.26.2
- 0.26.3
- 0.27.1
- 0.27.2
- 0.27.3
- 0.27.4
- 0.27.5
- 0.27.6
- 0.27.7
- 0.27.8
- 0.27.9
- 0.27.10
- 0.27.11
- 0.27.12
- 0.27.13
- 0.27.14
- 0.27.14.2
- 0.27.14.3
author: jeremy@seereason.com
latest: 0.27.14.3
description-type: haddock
description: A collection of types and functions that ensure that URLs generated by
  an application are valid. Need more properties here.
license-name: BSD-3-Clause
