all-versions:
- 1.0.0
- 1.0.1
- 1.0.2
- 1.0.3
- 1.0.4
- 1.0.5
- 1.1.0
- 1.1.1
- 1.2.0
author: Raghu Kaippully
basic-deps:
  arrows: '>=0.4 && <0.5'
  base: '>=4.13.0.0 && <4.20'
  http-media: '>=0.8 && <0.9'
  http-types: '>=0.12 && <0.13'
  insert-ordered-containers: '>=0.2 && <0.3'
  lens: '>=4.18.1 && <5.3'
  openapi3: '>=3.1.0 && <3.3'
  text: '>=1.2.0.0 && <2.2'
  webgear-core: ^>=1.2.0
changelog: |
  # Changelog for webgear-openapi

  ## [Unreleased]

  ## [1.2.0] - 2024-03-18

  ### Added
  - Prerequisite traits (#37)

  ## [1.1.1] - 2024-01-01

  ### Changed
  - Updated dependency bounds and GHC versions (#35)

  ## [1.1.0] - 2023-12-29

  ### Added
  - Streaming responses support (#26)
  - Support for cookies (#29)
  - Support file uploads (#32)

  ### Changed
  - Redesign APIs for ease of use (breaking change) (#24)

  ## [1.0.5] - 2023-05-04

  ### Changed
  - Update dependency bounds and GHC versions

  ## [1.0.4] - 2022-08-27

  ### Changed
  - Update dependency bounds and GHC versions

  ## [1.0.3] - 2022-06-26

  ### Changed
  - Nix flake based development environment

  ## [1.0.2] - 2022-06-11

  ### Changed
  - Upgrade to latest GHC versions (#9)

  ## [1.0.1] - 2022-01-09

  ### Changed
  - Update dependency bounds (#7)

  ## [1.0.0] - 2022-01-08

  ### Added
  - First version of webgear-openapi

  [Unreleased]: https://github.com/haskell-webgear/webgear/compare/v1.2.0...HEAD
  [1.2.0]: https://github.com/haskell-webgear/webgear/releases/tag/v1.2.0
  [1.1.1]: https://github.com/haskell-webgear/webgear/releases/tag/v1.1.1
  [1.1.0]: https://github.com/haskell-webgear/webgear/releases/tag/v1.1.0
  [1.0.5]: https://github.com/haskell-webgear/webgear/releases/tag/v1.0.5
  [1.0.4]: https://github.com/haskell-webgear/webgear/releases/tag/v1.0.4
  [1.0.3]: https://github.com/haskell-webgear/webgear/releases/tag/v1.0.3
  [1.0.2]: https://github.com/haskell-webgear/webgear/releases/tag/v1.0.2
  [1.0.1]: https://github.com/haskell-webgear/webgear/releases/tag/v1.0.1
  [1.0.0]: https://github.com/haskell-webgear/webgear/releases/tag/v1.0.0
changelog-type: markdown
description: |
  # WebGear - HTTP API server

  [![Hackage](https://img.shields.io/hackage/v/webgear-openapi)](https://hackage.haskell.org/package/webgear-openapi)

  WebGear is a Haskell library for building composable, type-safe HTTP APIs. This package helps to generate OpenAPI
  specifications from WebGear API specifications.
description-type: markdown
hash: 46f03a3b2c85dbee77c4edb9f0f1896bb83f026d050188b67b4ce0aceb548bcd
homepage: https://github.com/haskell-webgear/webgear#readme
latest: 1.2.0
license-name: MPL-2.0
maintainer: rkaippully@gmail.com
synopsis: Composable, type-safe library to build HTTP API servers
test-bench-deps: {}
