all-versions:
- 1.1.0
- 1.1.1
author: Raghu Kaippully
basic-deps:
  arrows: '>=0.4 && <0.5'
  base: '>=4.13.0.0 && <4.19'
  http-types: '>=0.12 && <0.13'
  insert-ordered-containers: '>=0.2 && <0.3'
  lens: '>=4.18.1 && <5.3'
  swagger2: '>=2.6 && <2.9'
  text: '>=1.2.0.0 && <2.2'
  webgear-core: ^>=1.1.1
changelog: |
  # Changelog for webgear-swagger

  ## [Unreleased]

  ## [1.1.1] - 2024-01-01

  ### Changed
  - Updated dependency bounds and GHC versions (#35)

  ## [1.1.0] - 2023-12-29

  ### Added
  - Streaming responses support (#26)
  - Support for cookies (#29)
  - Support file uploads (#32)
  - First version of webgear-swagger

  [Unreleased]: https://github.com/haskell-webgear/webgear/compare/v1.1.1...HEAD
  [1.1.1]: https://github.com/haskell-webgear/webgear/releases/tag/v1.1.1
  [1.1.0]: https://github.com/haskell-webgear/webgear/releases/tag/v1.1.0
changelog-type: markdown
description: |
  # WebGear - HTTP API server

  [![Hackage](https://img.shields.io/hackage/v/webgear-swagger)](https://hackage.haskell.org/package/webgear-swagger)

  WebGear is a Haskell library for building composable, type-safe HTTP APIs. This package helps to generate Swagger 2.0
  specifications from WebGear API specifications.
description-type: markdown
hash: 3a79f99f067358f71c34705ebe2fc056c05268c7873fc847d4a94623b5a4ff38
homepage: https://github.com/haskell-webgear/webgear#readme
latest: 1.1.1
license-name: MPL-2.0
maintainer: rkaippully@gmail.com
synopsis: Composable, type-safe library to build HTTP API servers
test-bench-deps: {}
