homepage: https://github.com/fimad/prometheus-haskell
changelog-type: ''
hash: 49c66cb52200363b4fe4254dca96ddb0c587f076673e29d530e8864e6f8bc362
test-bench-deps:
  exceptions: -any
  bytestring: -any
  stm: -any
  base: ! '>=4.7 && <5'
  hspec: -any
  text: -any
  clock: -any
  criterion: ! '>=1.2'
  doctest: -any
  random-shuffle: -any
  containers: -any
  utf8-string: -any
  atomic-primops: -any
  mtl: -any
  transformers: -any
  random: -any
  deepseq: -any
  QuickCheck: -any
  prometheus-client: -any
  transformers-compat: -any
maintainer: willcoster@gmail.com
synopsis: Haskell client library for http://prometheus.io.
changelog: ''
basic-deps:
  exceptions: -any
  bytestring: ! '>=0.9'
  stm: ! '>=2.3'
  base: ! '>=4.7 && <5'
  text: -any
  clock: -any
  containers: -any
  utf8-string: -any
  atomic-primops: ! '>=0.4'
  mtl: ! '>=2'
  transformers: -any
  deepseq: -any
  transformers-compat: -any
all-versions:
- '0.1.0.0'
- '0.1.0.1'
- '0.1.1'
- '0.2.0'
- '0.3.0'
- '1.0.0'
author: Will Coster
latest: '1.0.0'
description-type: haddock
description: Haskell client library for http://prometheus.io.
license-name: Apache-2.0
