all-versions:
- 0.0.0.0
- 0.0.0.1
- 0.1.0.0
- 0.2.0.0
- 0.2.0.1
author: Tom Sydney Kerckhove
basic-deps:
  base: '>=4.7 && <5'
  bytestring: '>=0'
  containers: '>=0'
  http-types: '>=0'
  prometheus: '>=0'
  text: '>=0'
  wai: '>=0'
changelog: |+
  # Changelog

  ## [0.2.0.1] - 2025-12-18

  ### Changed

  * Fixed that the caching mechanism was completely broken: it would never
    refresh the samples, ever.

  ## [0.2.0.0] - 2025-12-17

  ### Added

  * Support for sample caching in the metrics endpoint middleware

  ### Changed

  * Simplify the metrics endpoint API even further

  ## [0.1.0.0] - 2025-12-17

  ### Changed

  * Changed the metricsEndpointMiddleware API to support more bells and whistles
    without breaking the API in the future.

  ## [0.0.0.1] - 2025-07-14

  ### Added

  - `--skip-passed`: Skip passing tests and rerun once the entire suite is
    skipped.

changelog-type: markdown
description: Prometheus metrics for WAI applications
description-type: haddock
hash: 94cbb655cf28b8e5676447244f780552d5a6a53fa979cc84e2e6139a8e2925dd
homepage: https://github.com/NorfairKing/prometheus-wai#readme
latest: 0.2.0.1
license-name: MIT
maintainer: syd@cs-syd.eu
synopsis: ''
test-bench-deps: {}
...
