homepage: https://github.com/athanclark/nested-routes#readme
changelog-type: ''
hash: 70d7888d8d7892e566e46bc1d8f3f9946df420b52b03859d79a152131a019e9d
test-bench-deps:
  pred-trie: ! '>=0.6.1'
  exceptions: -any
  wai: ! '>=3.2.1'
  wai-transformers: ! '>=0.1.0'
  base: -any
  unordered-containers: -any
  hspec: -any
  text: -any
  extractable-singleton: -any
  tasty-hspec: -any
  tries: ! '>=0.0.6'
  regex-compat: -any
  wai-middleware-content-type: ! '>=0.6.2'
  hspec-wai: -any
  nested-routes: -any
  monad-control-aligned: -any
  mtl: -any
  hashable: -any
  poly-arity: ! '>=0.0.7'
  attoparsec: -any
  tasty: -any
  errors: -any
  wai-middleware-verbs: ! '>=0.4.0.1'
  http-types: -any
maintainer: Athan Clark <athan.clark@gmail.com>
synopsis: Declarative, compositional Wai responses
changelog: ''
basic-deps:
  pred-trie: ! '>=0.6.1'
  exceptions: -any
  wai: ! '>=3.2.1'
  wai-transformers: ! '>=0.1.0'
  base: ! '>=4.11 && <5'
  unordered-containers: -any
  text: -any
  extractable-singleton: -any
  tries: ! '>=0.0.6'
  regex-compat: -any
  wai-middleware-content-type: ! '>=0.6.2'
  monad-control-aligned: -any
  mtl: -any
  hashable: -any
  poly-arity: ! '>=0.0.7'
  attoparsec: -any
  errors: -any
  wai-middleware-verbs: ! '>=0.4.0.1'
all-versions:
- 6.1.0
- 7.0.0
- 7.1.0.1
- 7.1.1
- 7.2.0
- 7.2.1
- 7.2.2
- 8.0.0
- 8.0.1
- 8.0.2
- 8.1.0
- 8.2.0
- 9.0.0
- 9.0.0.1
- 9.0.1.0
- 9.0.1.1
- 9.0.2
author: ''
latest: 9.0.2
description-type: haddock
description: Please see the README on Github at <https://github.com/athanclark/nested-routes#readme>
license-name: BSD-3-Clause
