homepage: https://github.com/athanclark/nested-routes#readme
changelog-type: ''
hash: 44d80c8404545a509ed5ac665aeef69b53b17aebc6bce62baa1107bcacf23e36
test-bench-deps:
  pred-trie: ! '>=0.6.0'
  exceptions: -any
  wai: ! '>=3.2.1'
  wai-transformers: ! '>=0.1.0'
  base: -any
  unordered-containers: -any
  hspec: -any
  text: -any
  extractable-singleton: -any
  tasty-hspec: -any
  tries: ! '>=0.0.5'
  regex-compat: -any
  wai-middleware-content-type: ! '>=0.6.1.1'
  hspec-wai: -any
  nested-routes: -any
  monad-control-aligned: -any
  mtl: -any
  hashable: -any
  poly-arity: ! '>=0.0.7'
  attoparsec: -any
  tasty: -any
  errors: -any
  wai-middleware-verbs: ! '>=0.4.0.1'
  http-types: -any
maintainer: Athan Clark <athan.clark@gmail.com>
synopsis: Declarative, compositional Wai responses
changelog: ''
basic-deps:
  pred-trie: ! '>=0.6.0'
  exceptions: -any
  wai: ! '>=3.2.1'
  wai-transformers: ! '>=0.1.0'
  base: ! '>=4.9 && <5'
  unordered-containers: -any
  text: -any
  extractable-singleton: -any
  tries: ! '>=0.0.5'
  regex-compat: -any
  wai-middleware-content-type: ! '>=0.6.1.1'
  monad-control-aligned: -any
  mtl: -any
  hashable: -any
  poly-arity: ! '>=0.0.7'
  attoparsec: -any
  errors: -any
  wai-middleware-verbs: ! '>=0.4.0.1'
all-versions:
- '6.1.0'
- '7.0.0'
- '7.1.0.1'
- '7.1.1'
- '7.2.0'
- '7.2.1'
- '7.2.2'
- '8.0.0'
- '8.0.1'
- '8.0.2'
- '8.1.0'
- '8.2.0'
- '9.0.0'
- '9.0.0.1'
- '9.0.1.0'
- '9.0.1.1'
author: ''
latest: '9.0.1.1'
description-type: haddock
description: Please see the README on Github at <https://git.localcooking.com/tooling/pred-trie#readme>
license-name: BSD3
