all-versions:
- 0.1.0.0
author: Michael Ledger
basic-deps:
  aeson: '>=1.0.0.0 && <2.3'
  base: '>=4.16 && <5'
  openapi3: '>=3 && <4'
  primitive: '>=0.7.3.0'
  vector: '>=0.12.2.0'
changelog: |
  0.1.0.0 - 2026-01-28 Wed
  ========================
  Initial release
changelog-type: text
description: This package lets you derive ToJSON/FromJSON instances for record data-types
  that are encoded into tuples
description-type: haddock
hash: 9fd9ff4d3dd70b8d157a056306aa8cd5bca68d9cee6aee698a6d4b51f76e8855
homepage: ''
latest: 0.1.0.0
license-name: MPL-2.0
maintainer: mike@quasimal.com
synopsis: Encode and decode Haskell records as JSON tuples
test-bench-deps:
  QuickCheck: '>=0'
  aeson: '>=0'
  aeson-openapi-record-as-tuple: '>=0'
  base: '>=0'
  bytestring: '>=0'
  generic-random: '>=0'
  hspec: '>=0'
